name: deploy MiniSipServer to ghcr.io
on:
  push:
    paths:
      - docker/*
      - docker/Dockerfile
  workflow_dispatch:
jobs:
  docker-minisipserver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: './docker/'
    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and Deploy Docker Container'
        run: |
          docker build . --platform linux/amd64,linux/arm64 --tag ghcr.io/derkalle4/docker-minisipserver:latest
          docker push ghcr.io/derkalle4/docker-minisipserver:latest
