name: deploy MiniSipServer (Linux) to ghcr.io
on:
  push:
    paths:
      - docker-linux/*
      - docker-linux/Dockerfile
  workflow_dispatch:
jobs:
  docker-minisipserver:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: './docker-linux/'
    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@main
      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and Deploy Docker Container'
        uses: docker/build-push-action@v5
        with:
          context: ./docker-linux
          platforms: linux/amd64
          push: true
          tags: ghcr.io/derkalle4/docker-minisipserver:latest