name: deploy MiniSipServer-V60-U20 to ghcr.io
on:
  push:
    paths:
      - docker/v60/u20/*
      - docker/v60/u20/Dockerfile
  workflow_dispatch:
jobs:
  docker-docker-minisipserver-v60-u20:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    defaults:
      run:
        working-directory: './docker/v60/u20/'
    steps:
      - name: 'Checkout Source Code'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: 'Build and Deploy Docker Container'
        run: |
          docker build . --tag ghcr.io/derkalle4/docker-minisipserver-v60-u20:latest
          docker push ghcr.io/derkalle4/docker-minisipserver-v60-u20:latest
